# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45a917cc90d4b1ee0acc29e622c182c64ecc42a64bef8c641b78a84875e32f678d2449cef9c8dd173db370631123a7d9558390313e6c33b3efdb439b4182cf61

test:
  secret_key_base: c66d5ab6b4cac865461e2a0f655b2532fe095b306db04503806f6505c23dbf96fe1e3e0d8ed1b5ed8d78f531f50b7ea5aeb1affdf483b55965dba1dcb2313d5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
